### ISSUE TITLE
Limit (and prefix) are being ignored in list method

### ISSUE THREAD

**Issue by lgiavedoni** [misaelnieto/vercel-storage#4]
Hi,

I am trying to make use of the list method and sending options, but neither the limit or prefix seem to be working.

Basic code example:

blob.list(options={'limit': '1'}) returns all the results. (way more than 1)

Thanks for your support and the great work

**Comment by misaelnieto** [comment]
Thanks for the report! I'll look into it.

-- Noe

**Comment by lgiavedoni** [comment]
Thanks @misaelnieto, 
Please let me know when you have any update. I am also happy to support in any way.

**Comment by misaelnieto** [comment]
I added some unit tests to ensure the list() method is sending the correct parameters and It does.  I'll check with the actual service later.
